# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-GnuPG
version:      0.08
version_from: GnuPG.pm
installdirs:  site
requires:
    File::Spec:                    0
    File::Temp:                    0
    GnuPG::Interface:              0
    IO::Handle:                    0
    Mail::Address:                 0
    MIME::Entity:                  0
    MIME::Parser:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
