--- #YAML:1.0
name:                Mail-GnuPG
version:             0.15
abstract:            Process email with GPG.
license:             ~
author:              
    - Robert Spier <rspier@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Spec:                    0
    File::Temp:                    0
    GnuPG::Interface:              0
    IO::Handle:                    0
    Mail::Address:                 0
    MIME::Entity:                  0
    MIME::Parser:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
